import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Archivo_Black, Dela_Gothic_One } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react"
import { Toaster } from "@/components/ui/sonner"
import Background3DIcon from "@/components/TOP PAGE/BackGround3D";

const valorant = Archivo_Black({
  weight: "400",
  subsets: ["latin"]
})
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RANT BIGINER",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${valorant.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black text-white p-0 m-0 ">
        <SessionProvider>
          <Background3DIcon />
          <main 
          className="min-h-full flex flex-col  text-white p-0 m-0 "
          style={{ position: "relative", zIndex: 1 }}>
            {children}
          </main>
          <Toaster position="top-center" />
        </SessionProvider>
      </body>
    </html>
  );
}
