import type { Metadata } from "next";
import { Geist, Geist_Mono,Archivo_Black } from "next/font/google";
import "./globals.css";

const valorant = Archivo_Black({
  weight :"400",
  subsets: ["latin"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RANT BIGINER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${valorant.className} h-full antialiased`} 
    >
      <body className="min-h-full flex flex-col bg-white p-0 m-0">{children}</body>
    </html>
  );
}
